# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Math_app', '0003_auto_20170530_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='refs',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='refs',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='refs',
        ),
        migrations.DeleteModel(
            name='Ref',
        ),
    ]
