# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_app', '0007_auto_20170530_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='test_field_0',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='test_field_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
