# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Math_app', '0008_auto_20170601_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ref',
            name='test_field_0',
        ),
        migrations.RemoveField(
            model_name='ref',
            name='test_field_1',
        ),
    ]
