branch-defaults:
  master:
    environment: MathEnv
    group_suffix: null

global:
  application_name: MathApp
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
