# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_app', '0004_auto_20170530_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('url', models.URLField(max_length=1339, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='problem_refs', to='Math_app.Ref'),
        ),
        migrations.AddField(
            model_name='solution',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='solution_refs', to='Math_app.Ref'),
        ),
        migrations.AddField(
            model_name='topic',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='topic_refs', to='Math_app.Ref'),
        ),
    ]
