# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Math_app', '0006_auto_20170530_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1339, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='problem_refs', to='Math_app.Ref'),
        ),
        migrations.AddField(
            model_name='solution',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='solution_refs', to='Math_app.Ref'),
        ),
        migrations.AddField(
            model_name='topic',
            name='refs',
            field=models.ManyToManyField(blank=True, related_name='topic_refs', to='Math_app.Ref'),
        ),
    ]
